// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum AdPosition implements com.dyuproject.protostuff.EnumLite<AdPosition> {
    AD_POSITION_UNKNOWN(0),
    AD_POSITION_ABOVE_THE_FOLD(1),
    AD_POSITION_NOT_DEFINITE(2),
    AD_POSITION_BELOW_THE_FOLD(3),
    AD_POSITION_HEADER(4),
    AD_POSITION_FOOTER(5),
    AD_POSITION_SIDEBAR(6),
    AD_POSITION_FULLSCREEN(7);

    public final int number;

    private AdPosition(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static AdPosition valueOf(int number) {
        switch (number) {
            case 0:
                return AD_POSITION_UNKNOWN;
            case 1:
                return AD_POSITION_ABOVE_THE_FOLD;
            case 2:
                return AD_POSITION_NOT_DEFINITE;
            case 3:
                return AD_POSITION_BELOW_THE_FOLD;
            case 4:
                return AD_POSITION_HEADER;
            case 5:
                return AD_POSITION_FOOTER;
            case 6:
                return AD_POSITION_SIDEBAR;
            case 7:
                return AD_POSITION_FULLSCREEN;
            default:
                return null;
        }
    }
}
