// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class App implements Externalizable, Message<App> {

    public static Schema<App> getSchema() {
        return SCHEMA;
    }

    public static App getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    static final App DEFAULT_INSTANCE = new App();


    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String id;
    String name;
    String domain;
    List<String> cat;
    List<String> sectioncat;
    List<String> pagecat;
    String ver;
    String bundle;
    Bool privacypolicy;
    Integer paid;
    Publisher publisher;
    Content content;
    String keywords;
    String storeurl;

    public App() {

    }

    // getters and setters

    // id

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    // name

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // domain

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    // cat

    public List<String> getCatList() {
        return cat;
    }

    public void setCatList(List<String> cat) {
        this.cat = cat;
    }

    // sectioncat

    public List<String> getSectioncatList() {
        return sectioncat;
    }

    public void setSectioncatList(List<String> sectioncat) {
        this.sectioncat = sectioncat;
    }

    // pagecat

    public List<String> getPagecatList() {
        return pagecat;
    }

    public void setPagecatList(List<String> pagecat) {
        this.pagecat = pagecat;
    }

    // ver

    public String getVer() {
        return ver;
    }

    public void setVer(String ver) {
        this.ver = ver;
    }

    // bundle

    public String getBundle() {
        return bundle;
    }

    public void setBundle(String bundle) {
        this.bundle = bundle;
    }

    // privacypolicy

    public Bool getPrivacypolicy() {
        return privacypolicy == null ? Bool.FALSE : privacypolicy;
    }

    public void setPrivacypolicy(Bool privacypolicy) {
        this.privacypolicy = privacypolicy;
    }

    // paid

    public Integer getPaid() {
        return paid;
    }

    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    // publisher

    public Publisher getPublisher() {
        return publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    // content

    public Content getContent() {
        return content;
    }

    public void setContent(Content content) {
        this.content = content;
    }

    // keywords

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    // storeurl

    public String getStoreurl() {
        return storeurl;
    }

    public void setStoreurl(String storeurl) {
        this.storeurl = storeurl;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<App> cachedSchema() {
        return SCHEMA;
    }

    static final Schema<App> SCHEMA = new Schema<App>() {
        // schema methods

        public App newMessage() {
            return new App();
        }

        public Class<App> typeClass() {
            return App.class;
        }

        public String messageName() {
            return App.class.getSimpleName();
        }

        public String messageFullName() {
            return App.class.getName();
        }

        public boolean isInitialized(App message) {
            return true;
        }

        public void mergeFrom(Input input, App message) throws IOException {
            for (int number = input.readFieldNumber(this); ; number = input.readFieldNumber(this)) {
                switch (number) {
                    case 0:
                        return;
                    case 1:
                        message.id = input.readString();
                        break;
                    case 2:
                        message.name = input.readString();
                        break;
                    case 3:
                        message.domain = input.readString();
                        break;
                    case 4:
                        if (message.cat == null)
                            message.cat = new ArrayList<String>();
                        message.cat.add(input.readString());
                        break;
                    case 5:
                        if (message.sectioncat == null)
                            message.sectioncat = new ArrayList<String>();
                        message.sectioncat.add(input.readString());
                        break;
                    case 6:
                        if (message.pagecat == null)
                            message.pagecat = new ArrayList<String>();
                        message.pagecat.add(input.readString());
                        break;
                    case 7:
                        message.ver = input.readString();
                        break;
                    case 8:
                        message.bundle = input.readString();
                        break;
                    case 9:
                        message.privacypolicy = Bool.valueOf(input.readEnum());
                        break;
                    case 10:
                        message.paid = input.readInt32();
                        break;
                    case 11:
                        message.publisher = input.mergeObject(message.publisher, Publisher.getSchema());
                        break;

                    case 12:
                        message.content = input.mergeObject(message.content, Content.getSchema());
                        break;

                    case 13:
                        message.keywords = input.readString();
                        break;
                    case 14:
                        message.storeurl = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }
            }
        }


        public void writeTo(Output output, App message) throws IOException {
            if (message.id != null)
                output.writeString(1, message.id, false);

            if (message.name != null)
                output.writeString(2, message.name, false);

            if (message.domain != null)
                output.writeString(3, message.domain, false);

            if (message.cat != null) {
                for (String cat : message.cat) {
                    if (cat != null)
                        output.writeString(4, cat, true);
                }
            }

            if (message.sectioncat != null) {
                for (String sectioncat : message.sectioncat) {
                    if (sectioncat != null)
                        output.writeString(5, sectioncat, true);
                }
            }

            if (message.pagecat != null) {
                for (String pagecat : message.pagecat) {
                    if (pagecat != null)
                        output.writeString(6, pagecat, true);
                }
            }

            if (message.ver != null)
                output.writeString(7, message.ver, false);

            if (message.bundle != null)
                output.writeString(8, message.bundle, false);

            if (message.privacypolicy != null)
                output.writeEnum(9, message.privacypolicy.number, false);

            if (message.paid != null)
                output.writeInt32(10, message.paid, false);

            if (message.publisher != null)
                output.writeObject(11, message.publisher, Publisher.getSchema(), false);


            if (message.content != null)
                output.writeObject(12, message.content, Content.getSchema(), false);


            if (message.keywords != null)
                output.writeString(13, message.keywords, false);

            if (message.storeurl != null)
                output.writeString(14, message.storeurl, false);
        }

        public String getFieldName(int number) {
            switch (number) {
                case 1:
                    return "id";
                case 2:
                    return "name";
                case 3:
                    return "domain";
                case 4:
                    return "cat";
                case 5:
                    return "sectioncat";
                case 6:
                    return "pagecat";
                case 7:
                    return "ver";
                case 8:
                    return "bundle";
                case 9:
                    return "privacypolicy";
                case 10:
                    return "paid";
                case 11:
                    return "publisher";
                case 12:
                    return "content";
                case 13:
                    return "keywords";
                case 14:
                    return "storeurl";
                default:
                    return null;
            }
        }

        public int getFieldNumber(String name) {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();

        {
            fieldMap.put("id", 1);
            fieldMap.put("name", 2);
            fieldMap.put("domain", 3);
            fieldMap.put("cat", 4);
            fieldMap.put("sectioncat", 5);
            fieldMap.put("pagecat", 6);
            fieldMap.put("ver", 7);
            fieldMap.put("bundle", 8);
            fieldMap.put("privacypolicy", 9);
            fieldMap.put("paid", 10);
            fieldMap.put("publisher", 11);
            fieldMap.put("content", 12);
            fieldMap.put("keywords", 13);
            fieldMap.put("storeurl", 14);
        }
    };

}
