// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class BidSet implements Externalizable, Message<BidSet> {

    public static Schema<BidSet> getSchema() {
        return SCHEMA;
    }

    public static BidSet getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    static final BidSet DEFAULT_INSTANCE = new BidSet();


    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Bid> bids;
    String seat;
    Boolean group;

    public BidSet() {

    }

    // getters and setters

    // bids

    public List<Bid> getBidsList() {
        return bids;
    }

    public void setBidsList(List<Bid> bids) {
        this.bids = bids;
    }

    // seat

    public String getSeat() {
        return seat;
    }

    public void setSeat(String seat) {
        this.seat = seat;
    }

    // group

    public Boolean getGroup() {
        return group;
    }

    public void setGroup(Boolean group) {
        this.group = group;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<BidSet> cachedSchema() {
        return SCHEMA;
    }

    static final Schema<BidSet> SCHEMA = new Schema<BidSet>() {
        // schema methods

        public BidSet newMessage() {
            return new BidSet();
        }

        public Class<BidSet> typeClass() {
            return BidSet.class;
        }

        public String messageName() {
            return BidSet.class.getSimpleName();
        }

        public String messageFullName() {
            return BidSet.class.getName();
        }

        public boolean isInitialized(BidSet message) {
            return true;
        }

        public void mergeFrom(Input input, BidSet message) throws IOException {
            for (int number = input.readFieldNumber(this); ; number = input.readFieldNumber(this)) {
                switch (number) {
                    case 0:
                        return;
                    case 1:
                        if (message.bids == null)
                            message.bids = new ArrayList<Bid>();
                        message.bids.add(input.mergeObject(null, Bid.getSchema()));
                        break;

                    case 2:
                        message.seat = input.readString();
                        break;
                    case 3:
                        message.group = input.readBool();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }
            }
        }


        public void writeTo(Output output, BidSet message) throws IOException {
            if (message.bids != null) {
                for (Bid bids : message.bids) {
                    if (bids != null)
                        output.writeObject(1, bids, Bid.getSchema(), true);
                }
            }


            if (message.seat != null)
                output.writeString(2, message.seat, false);

            if (message.group != null)
                output.writeBool(3, message.group, false);
        }

        public String getFieldName(int number) {
            switch (number) {
                case 1:
                    return "bids";
                case 2:
                    return "seat";
                case 3:
                    return "group";
                default:
                    return null;
            }
        }

        public int getFieldNumber(String name) {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();

        {
            fieldMap.put("bids", 1);
            fieldMap.put("seat", 2);
            fieldMap.put("group", 3);
        }
    };

}
