// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum Bool implements com.dyuproject.protostuff.EnumLite<Bool> {
    FALSE(0),
    TRUE(1);

    public final int number;

    private Bool(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static Bool valueOf(int number) {
        switch (number) {
            case 0:
                return FALSE;
            case 1:
                return TRUE;
            default:
                return null;
        }
    }
}
