// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum ContentDeliveryMethod implements com.dyuproject.protostuff.EnumLite<ContentDeliveryMethod> {
    CONTENT_DELIVERY_METHOD_STREAMING(1),
    CONTENT_DELIVERY_METHOD_PROGRESSIVE(2);

    public final int number;

    private ContentDeliveryMethod(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static ContentDeliveryMethod valueOf(int number) {
        switch (number) {
            case 1:
                return CONTENT_DELIVERY_METHOD_STREAMING;
            case 2:
                return CONTENT_DELIVERY_METHOD_PROGRESSIVE;
            default:
                return null;
        }
    }
}
