// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum CreativeAttribute implements com.dyuproject.protostuff.EnumLite<CreativeAttribute> {
    CREATIVE_ATTRIBUTE_AUDIO_AD_AUTO_PLAY(1),
    CREATIVE_ATTRIBUTE_AUDIO_AD_USER_INITIATED(2),
    CREATIVE_ATTRIBUTE_EXPANDABLE_AUTOMATIC(3),
    CREATIVE_ATTRIBUTE_EXPANDABLE_USER_INITIATED_CLICK(4),
    CREATIVE_ATTRIBUTE_EXPANDABLE_USER_INITIATED_ROLLOVER(5),
    CREATIVE_ATTRIBUTE_IN_BANNER_VIDEO_AD_AUTO_PLAY(6),
    CREATIVE_ATTRIBUTE_IN_BANNER_VIDEO_AD_USER_INITIATED(7),
    CREATIVE_ATTRIBUTE_POP(8),
    CREATIVE_ATTRIBUTE_PROVOCATIVE_OR_SUGGESTIVE_IMAGERY(9),
    CREATIVE_ATTRIBUTE_SHAKING_FLASHING_FLICKERING_SMILEYS(10),
    CREATIVE_ATTRIBUTE_SURVEYS(11),
    CREATIVE_ATTRIBUTE_TEXT_ONLY(12),
    CREATIVE_ATTRIBUTE_USER_INTERACTIVE(13),
    CREATIVE_ATTRIBUTE_WINDOWS_DIALOG_ALERT_STYLE(14),
    CREATIVE_ATTRIBUTE_HAS_AUDIO_ON_OF_BUTTON(15),
    CREATIVE_ATTRIBUTE_AD_CAN_BE_SKIPPED(16);

    public final int number;

    private CreativeAttribute(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static CreativeAttribute valueOf(int number) {
        switch (number) {
            case 1:
                return CREATIVE_ATTRIBUTE_AUDIO_AD_AUTO_PLAY;
            case 2:
                return CREATIVE_ATTRIBUTE_AUDIO_AD_USER_INITIATED;
            case 3:
                return CREATIVE_ATTRIBUTE_EXPANDABLE_AUTOMATIC;
            case 4:
                return CREATIVE_ATTRIBUTE_EXPANDABLE_USER_INITIATED_CLICK;
            case 5:
                return CREATIVE_ATTRIBUTE_EXPANDABLE_USER_INITIATED_ROLLOVER;
            case 6:
                return CREATIVE_ATTRIBUTE_IN_BANNER_VIDEO_AD_AUTO_PLAY;
            case 7:
                return CREATIVE_ATTRIBUTE_IN_BANNER_VIDEO_AD_USER_INITIATED;
            case 8:
                return CREATIVE_ATTRIBUTE_POP;
            case 9:
                return CREATIVE_ATTRIBUTE_PROVOCATIVE_OR_SUGGESTIVE_IMAGERY;
            case 10:
                return CREATIVE_ATTRIBUTE_SHAKING_FLASHING_FLICKERING_SMILEYS;
            case 11:
                return CREATIVE_ATTRIBUTE_SURVEYS;
            case 12:
                return CREATIVE_ATTRIBUTE_TEXT_ONLY;
            case 13:
                return CREATIVE_ATTRIBUTE_USER_INTERACTIVE;
            case 14:
                return CREATIVE_ATTRIBUTE_WINDOWS_DIALOG_ALERT_STYLE;
            case 15:
                return CREATIVE_ATTRIBUTE_HAS_AUDIO_ON_OF_BUTTON;
            case 16:
                return CREATIVE_ATTRIBUTE_AD_CAN_BE_SKIPPED;
            default:
                return null;
        }
    }
}
