// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum CreativeType implements com.dyuproject.protostuff.EnumLite<CreativeType> {
    CREATIVE_TYPE_TEXT_AD(1),
    CREATIVE_TYPE_BANNER_AD(2),
    CREATIVE_TYPE_JAVA_SCRIPT(3),
    CREATIVE_TYPE_IFRAME(4);

    public final int number;

    private CreativeType(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static CreativeType valueOf(int number) {
        switch (number) {
            case 1:
                return CREATIVE_TYPE_TEXT_AD;
            case 2:
                return CREATIVE_TYPE_BANNER_AD;
            case 3:
                return CREATIVE_TYPE_JAVA_SCRIPT;
            case 4:
                return CREATIVE_TYPE_IFRAME;
            default:
                return null;
        }
    }
}
