// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum ExpandableDirection implements com.dyuproject.protostuff.EnumLite<ExpandableDirection> {
    EXPANDABLE_DIRECTION_LEFT(1),
    EXPANDABLE_DIRECTION_RIGHT(2),
    EXPANDABLE_DIRECTION_UP(3),
    EXPANDABLE_DIRECTION_DOWN(4),
    EXPANDABLE_DIRECTION_FULLSCREEN(5);

    public final int number;

    private ExpandableDirection(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static ExpandableDirection valueOf(int number) {
        switch (number) {
            case 1:
                return EXPANDABLE_DIRECTION_LEFT;
            case 2:
                return EXPANDABLE_DIRECTION_RIGHT;
            case 3:
                return EXPANDABLE_DIRECTION_UP;
            case 4:
                return EXPANDABLE_DIRECTION_DOWN;
            case 5:
                return EXPANDABLE_DIRECTION_FULLSCREEN;
            default:
                return null;
        }
    }
}
