// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum Gender implements com.dyuproject.protostuff.EnumLite<Gender> {
    GENDER_UNKNOWN(0),
    GENDER_MALE(1),
    GENDER_FEMALE(2);

    public final int number;

    private Gender(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static Gender valueOf(int number) {
        switch (number) {
            case 0:
                return GENDER_UNKNOWN;
            case 1:
                return GENDER_MALE;
            case 2:
                return GENDER_FEMALE;
            default:
                return null;
        }
    }
}
