// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum NoBidReason implements com.dyuproject.protostuff.EnumLite<NoBidReason> {
    NO_BID_REASON_UNKNOWN(0),
    NO_BID_REASON_NOT_NEEDED(1),
    NO_BID_REASON_VIOLATED_FILTER(2),
    NO_BID_REASON_TECHNICAL_ERROR(3);

    public final int number;

    private NoBidReason(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static NoBidReason valueOf(int number) {
        switch (number) {
            case 0:
                return NO_BID_REASON_UNKNOWN;
            case 1:
                return NO_BID_REASON_NOT_NEEDED;
            case 2:
                return NO_BID_REASON_VIOLATED_FILTER;
            case 3:
                return NO_BID_REASON_TECHNICAL_ERROR;
            default:
                return null;
        }
    }
}
