// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum PriceUnit implements com.dyuproject.protostuff.EnumLite<PriceUnit> {
    PRICE_UNIT_PER_THOUSAND(0),
    PRICE_UNIT_PER_IMPRESSION(1),
    PRICE_UNIT_MICROS(2);

    public final int number;

    private PriceUnit(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static PriceUnit valueOf(int number) {
        switch (number) {
            case 0:
                return PRICE_UNIT_PER_THOUSAND;
            case 1:
                return PRICE_UNIT_PER_IMPRESSION;
            case 2:
                return PRICE_UNIT_MICROS;
            default:
                return null;
        }
    }
}
