// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum SourceRelationship implements com.dyuproject.protostuff.EnumLite<SourceRelationship> {
    SOURCE_RELATIONSHIP_INDIRECT(0),
    SOURCE_RELATIONSHIP_DIRECT(1);

    public final int number;

    private SourceRelationship(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static SourceRelationship valueOf(int number) {
        switch (number) {
            case 0:
                return SOURCE_RELATIONSHIP_INDIRECT;
            case 1:
                return SOURCE_RELATIONSHIP_DIRECT;
            default:
                return null;
        }
    }
}
