// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum VideoStartDelay implements com.dyuproject.protostuff.EnumLite<VideoStartDelay> {
    VIDEO_START_DELAY_PRE_ROLL(0),
    VIDEO_START_DELAY_MID_ROLL(-1),
    VIDEO_START_DELAY_POST_ROLL(-2);

    public final int number;

    private VideoStartDelay(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static VideoStartDelay valueOf(int number) {
        switch (number) {
            case -2:
                return VIDEO_START_DELAY_POST_ROLL;
            case -1:
                return VIDEO_START_DELAY_MID_ROLL;
            case 0:
                return VIDEO_START_DELAY_PRE_ROLL;
            default:
                return null;
        }
    }
}
