// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum VideoQuality implements com.dyuproject.protostuff.EnumLite<VideoQuality> {
    VIDEO_QUALITY_UNKNOWN(0),
    VIDEO_QUALITY_PROFESSIONALLY_PRODUCED(1),
    VIDEO_QUALITY_PROSUMER(2),
    VIDEO_QUALITY_USER_GENERATED(3);

    public final int number;

    private VideoQuality(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static VideoQuality valueOf(int number) {
        switch (number) {
            case 0:
                return VIDEO_QUALITY_UNKNOWN;
            case 1:
                return VIDEO_QUALITY_PROFESSIONALLY_PRODUCED;
            case 2:
                return VIDEO_QUALITY_PROSUMER;
            case 3:
                return VIDEO_QUALITY_USER_GENERATED;
            default:
                return null;
        }
    }
}
