// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum VideoLinearity implements com.dyuproject.protostuff.EnumLite<VideoLinearity> {
    VIDEO_LINEARITY_LINEAR(1),
    VIDEO_LINEARITY_NON_LINEAR(2);

    public final int number;

    private VideoLinearity(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static VideoLinearity valueOf(int number) {
        switch (number) {
            case 1:
                return VIDEO_LINEARITY_LINEAR;
            case 2:
                return VIDEO_LINEARITY_NON_LINEAR;
            default:
                return null;
        }
    }
}
