// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb;

public enum VideoPlaybackMethod implements com.dyuproject.protostuff.EnumLite<VideoPlaybackMethod> {
    VIDEO_PLAYBACK_METHOD_AUTO_PLAY_WITH_SOUND_ALLOWED(1),
    VIDEO_PLAYBACK_METHOD_AUTO_PLAY_WITH_SOUND_NOT_ALLOWED(2),
    VIDEO_PLAYBACK_METHOD_CLICK_TO_PLAY(3),
    VIDEO_PLAYBACK_METHOD_MOUSE_OVER(4);

    public final int number;

    private VideoPlaybackMethod(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static VideoPlaybackMethod valueOf(int number) {
        switch (number) {
            case 1:
                return VIDEO_PLAYBACK_METHOD_AUTO_PLAY_WITH_SOUND_ALLOWED;
            case 2:
                return VIDEO_PLAYBACK_METHOD_AUTO_PLAY_WITH_SOUND_NOT_ALLOWED;
            case 3:
                return VIDEO_PLAYBACK_METHOD_CLICK_TO_PLAY;
            case 4:
                return VIDEO_PLAYBACK_METHOD_MOUSE_OVER;
            default:
                return null;
        }
    }
}
