// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from openrtb.proto

package org.openrtb.mobile;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class App implements Externalizable, Message<App> {

    public static Schema<App> getSchema() {
        return SCHEMA;
    }

    public static App getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    static final App DEFAULT_INSTANCE = new App();


    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String aid;
    String name;
    String domain;
    String pid;
    String pub;
    String pdomain;
    List<String> cat;
    String keywords;
    String ver;
    String bundle;
    Integer paid;

    public App() {

    }

    // getters and setters

    // aid

    public String getAid() {
        return aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    // name

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // domain

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    // pid

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    // pub

    public String getPub() {
        return pub;
    }

    public void setPub(String pub) {
        this.pub = pub;
    }

    // pdomain

    public String getPdomain() {
        return pdomain;
    }

    public void setPdomain(String pdomain) {
        this.pdomain = pdomain;
    }

    // cat

    public List<String> getCatList() {
        return cat;
    }

    public void setCatList(List<String> cat) {
        this.cat = cat;
    }

    // keywords

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    // ver

    public String getVer() {
        return ver;
    }

    public void setVer(String ver) {
        this.ver = ver;
    }

    // bundle

    public String getBundle() {
        return bundle;
    }

    public void setBundle(String bundle) {
        this.bundle = bundle;
    }

    // paid

    public Integer getPaid() {
        return paid;
    }

    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<App> cachedSchema() {
        return SCHEMA;
    }

    static final Schema<App> SCHEMA = new Schema<App>() {
        // schema methods

        public App newMessage() {
            return new App();
        }

        public Class<App> typeClass() {
            return App.class;
        }

        public String messageName() {
            return App.class.getSimpleName();
        }

        public String messageFullName() {
            return App.class.getName();
        }

        public boolean isInitialized(App message) {
            return true;
        }

        public void mergeFrom(Input input, App message) throws IOException {
            for (int number = input.readFieldNumber(this); ; number = input.readFieldNumber(this)) {
                switch (number) {
                    case 0:
                        return;
                    case 1:
                        message.aid = input.readString();
                        break;
                    case 2:
                        message.name = input.readString();
                        break;
                    case 3:
                        message.domain = input.readString();
                        break;
                    case 4:
                        message.pid = input.readString();
                        break;
                    case 5:
                        message.pub = input.readString();
                        break;
                    case 6:
                        message.pdomain = input.readString();
                        break;
                    case 7:
                        if (message.cat == null)
                            message.cat = new ArrayList<String>();
                        message.cat.add(input.readString());
                        break;
                    case 8:
                        message.keywords = input.readString();
                        break;
                    case 9:
                        message.ver = input.readString();
                        break;
                    case 10:
                        message.bundle = input.readString();
                        break;
                    case 11:
                        message.paid = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }
            }
        }


        public void writeTo(Output output, App message) throws IOException {
            if (message.aid != null)
                output.writeString(1, message.aid, false);

            if (message.name != null)
                output.writeString(2, message.name, false);

            if (message.domain != null)
                output.writeString(3, message.domain, false);

            if (message.pid != null)
                output.writeString(4, message.pid, false);

            if (message.pub != null)
                output.writeString(5, message.pub, false);

            if (message.pdomain != null)
                output.writeString(6, message.pdomain, false);

            if (message.cat != null) {
                for (String cat : message.cat) {
                    if (cat != null)
                        output.writeString(7, cat, true);
                }
            }

            if (message.keywords != null)
                output.writeString(8, message.keywords, false);

            if (message.ver != null)
                output.writeString(9, message.ver, false);

            if (message.bundle != null)
                output.writeString(10, message.bundle, false);

            if (message.paid != null)
                output.writeInt32(11, message.paid, false);
        }

        public String getFieldName(int number) {
            switch (number) {
                case 1:
                    return "aid";
                case 2:
                    return "name";
                case 3:
                    return "domain";
                case 4:
                    return "pid";
                case 5:
                    return "pub";
                case 6:
                    return "pdomain";
                case 7:
                    return "cat";
                case 8:
                    return "keywords";
                case 9:
                    return "ver";
                case 10:
                    return "bundle";
                case 11:
                    return "paid";
                default:
                    return null;
            }
        }

        public int getFieldNumber(String name) {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();

        {
            fieldMap.put("aid", 1);
            fieldMap.put("name", 2);
            fieldMap.put("domain", 3);
            fieldMap.put("pid", 4);
            fieldMap.put("pub", 5);
            fieldMap.put("pdomain", 6);
            fieldMap.put("cat", 7);
            fieldMap.put("keywords", 8);
            fieldMap.put("ver", 9);
            fieldMap.put("bundle", 10);
            fieldMap.put("paid", 11);
        }
    };

}
